export type Category = "all" | "design" | "development";

export type WorkLink = {
  label: string;
  href: string;
  external?: boolean;
};

export type WorkProject = {
  id: string;
  title: string;
  category: ("design" | "development")[];
  thumb: string;
  summary: string;
  tags: string[];
  role: string[];
  highlights: string[];
  links: WorkLink[];
  websiteUrl?: string;
};

export const workProjects: WorkProject[] = [
  {
    id: "client-bike",
    title: "스토바이크 아카데미 홈페이지",
    category: ["design", "development"],
    thumb: "/featured/project-02.png",
    summary: "교육 예약과 운영 관리를 고려해 구축한 오토바이 아카데미 웹사이트입니다.",
    tags: ["Design", "Publishing", "Booking"],
    role: ["전체 페이지 UI 구현", "관리자 화면 구성", "예약 시스템 연동"],
    highlights: ["교육 예약 흐름에 맞춘 페이지 구성", "실제 운영 요구사항 반영", "PC/모바일 반응형 구현"],
    links: [{ label: "사이트 보기", href: "http://finesse.co.kr/home/" }],
    websiteUrl: "http://finesse.co.kr/home/",
  },
  {
    id: "client-01",
    title: "여행/투어 예약 사이트",
    category: ["design", "development"],
    thumb: "/projects/sample-01.png",
    summary: "서브 페이지 디자인, 반응형 퍼블리싱, 투어 게시판 커스텀을 진행했습니다.",
    tags: ["Design", "Publishing", "Board"],
    role: ["서브 페이지 디자인", "반응형 퍼블리싱", "투어 게시판 커스텀"],
    highlights: ["여행 상품 탐색 흐름 구성", "그누보드 기반 게시판 커스텀", "모바일 화면 대응"],
    links: [
      { label: "사이트 보기", href: "https://alleytour.com/home/" },
      { label: "투어 게시판", href: "https://alleytour.com/home/kkirikkiri_1gil" },
    ],
    websiteUrl: "https://alleytour.com/home/",
  },
  {
    id: "client-02",
    title: "기업 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-02.png",
    summary: "연혁, 제품, 카탈로그, 문의 게시판을 운영 구조에 맞게 커스텀했습니다.",
    tags: ["Publishing", "PHP", "Board"],
    role: ["반응형 퍼블리싱", "게시판 커스텀", "운영 콘텐츠 구조화"],
    highlights: ["연혁 게시판 구현", "제품/카탈로그 게시판 커스텀", "문의하기 흐름 구성"],
    links: [
      { label: "연혁 게시판", href: "https://www.autrol.com/kr/history" },
      { label: "제품 게시판", href: "https://www.autrol.com/kr/pressure/" },
      { label: "카탈로그", href: "https://www.autrol.com/kr/catalogue" },
      { label: "문의하기", href: "https://www.autrol.com/kr/inquiry" },
    ],
    websiteUrl: "https://www.autrol.com",
  },
  {
    id: "client-03",
    title: "블로그형 콘텐츠 사이트",
    category: ["development"],
    thumb: "/projects/sample-03.png",
    summary: "메인 페이지에 게시판 콘텐츠가 자연스럽게 노출되도록 구성했습니다.",
    tags: ["Publishing", "Content"],
    role: ["메인 화면 구성", "게시판 콘텐츠 노출", "반응형 퍼블리싱"],
    highlights: ["블로그형 콘텐츠 구조", "메인 게시글 노출", "간결한 정보 배치"],
    links: [{ label: "사이트 보기", href: "https://dev.cube-eye.co.kr/support/index.php" }],
    websiteUrl: "https://dev.cube-eye.co.kr/support/index.php",
  },
  {
    id: "client-04",
    title: "기업 제품 홈페이지",
    category: ["design", "development"],
    thumb: "/projects/sample-04.png",
    summary: "메인/제품 페이지 디자인과 반응형 퍼블리싱, 제품 게시판 커스텀을 담당했습니다.",
    tags: ["Design", "Publishing", "Product"],
    role: ["메인/제품 페이지 디자인", "반응형 퍼블리싱", "제품 게시판 커스텀"],
    highlights: ["제품 정보 중심 화면", "운영 가능한 게시판 구조", "브랜드 톤에 맞춘 이미지 배치"],
    links: [
      { label: "사이트 보기", href: "http://healingsound.kr" },
      { label: "제품 게시판", href: "http://healingsound.kr/home/bbs/board.php?bo_table=kr_pro_02&wr_id=1" },
    ],
    websiteUrl: "http://healingsound.kr",
  },
  {
    id: "client-05",
    title: "제조 기업 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-05.png",
    summary: "제품 게시판과 자료실 게시판을 커스텀하고 반응형 화면을 구현했습니다.",
    tags: ["Publishing", "Board"],
    role: ["반응형 퍼블리싱", "제품 게시판 커스텀", "자료실 게시판 커스텀"],
    highlights: ["제품 정보 관리 구조", "자료실 콘텐츠 연결", "기업형 레이아웃 구현"],
    links: [
      { label: "제품 게시판", href: "http://www.atlk.co.kr/home/pro" },
      { label: "자료실", href: "http://www.atlk.co.kr/home/case_01" },
    ],
    websiteUrl: "http://www.atlk.co.kr",
  },
  {
    id: "client-06",
    title: "글로벌 기업 홈페이지",
    category: ["design", "development"],
    thumb: "/projects/sample-06.png",
    summary: "서브 페이지 디자인, 반응형 퍼블리싱, 제품 게시판 커스텀을 진행했습니다.",
    tags: ["Design", "Publishing"],
    role: ["서브 페이지 디자인", "반응형 퍼블리싱", "제품 게시판 커스텀"],
    highlights: ["제품군별 정보 구조", "글로벌 기업 톤 반영", "운영 게시판 연결"],
    links: [
      { label: "사이트 보기", href: "https://sunwooglobal.co.kr" },
      { label: "제품 게시판", href: "https://sunwooglobal.co.kr/home/bbs/board.php?bo_table=pro05_02&wr_id=1" },
    ],
    websiteUrl: "https://sunwooglobal.co.kr",
  },
  {
    id: "client-07",
    title: "장비 기업 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-07.png",
    summary: "제품 카테고리와 상세 게시판이 연결되는 화면을 구현했습니다.",
    tags: ["Publishing", "Product"],
    role: ["반응형 퍼블리싱", "제품 게시판 커스텀", "카테고리 화면 구성"],
    highlights: ["제품 카테고리 탐색", "상세 게시글 연결", "장비 이미지 중심 화면"],
    links: [
      {
        label: "제품 게시판",
        href: "http://dcseng.co.kr/home/bbs/board.php?bo_table=pro_01&sca=%EC%98%A4%EB%B9%84%ED%83%88+%EC%88%98%EB%8F%99+%EC%9E%A5%EB%B9%84",
      },
    ],
    websiteUrl: "http://dcseng.co.kr",
  },
  {
    id: "client-08",
    title: "무역 기업 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-08.png",
    summary: "제품 게시판과 문의하기 게시판을 포함한 기업 사이트를 제작했습니다.",
    tags: ["Publishing", "Inquiry"],
    role: ["반응형 퍼블리싱", "제품 게시판 커스텀", "문의하기 게시판 커스텀"],
    highlights: ["제품 조달 정보 구조", "문의 접점 구성", "기업 소개 화면 구현"],
    links: [
      { label: "제품 게시판", href: "http://www.witconintl.com/home/bbs/board.php?bo_table=procure01" },
      { label: "문의하기", href: "http://www.witconintl.com/home/bbs/board.php?bo_table=inquiry_test" },
    ],
    websiteUrl: "http://www.witconintl.com",
  },
  {
    id: "client-09",
    title: "체험 예약 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-09.png",
    summary: "체험 예약 관리 게시판을 커스텀하고 예약 흐름을 정리했습니다.",
    tags: ["Publishing", "Booking"],
    role: ["반응형 퍼블리싱", "예약 게시판 커스텀", "운영 화면 구성"],
    highlights: ["체험 예약 관리", "예약 목록 운영", "모바일 사용자 흐름 대응"],
    links: [
      {
        label: "예약 게시판",
        href: "https://www.xn--ob0bz2e28lwrgda258dg5cka.com/home/bbs/board.php?bo_table=booking_kr",
      },
    ],
    websiteUrl: "https://www.xn--ob0bz2e28lwrgda258dg5cka.com",
  },
  {
    id: "client-10",
    title: "브랜드 기업 홈페이지",
    category: ["design", "development"],
    thumb: "/projects/sample-10.png",
    summary: "메인 배너와 서브 페이지 디자인, 반응형 퍼블리싱을 진행했습니다.",
    tags: ["Design", "Publishing"],
    role: ["메인 배너 디자인", "서브 페이지 디자인", "반응형 퍼블리싱"],
    highlights: ["브랜드 이미지 중심 배너", "서브 페이지 톤 정리", "기업형 반응형 화면"],
    links: [{ label: "사이트 보기", href: "https://www.psiplus.co.kr/home/" }],
    websiteUrl: "https://www.psiplus.co.kr/home/",
  },
  {
    id: "client-11",
    title: "테크 기업 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-11.png",
    summary: "메인 페이지 중심의 반응형 퍼블리싱을 담당했습니다.",
    tags: ["Publishing"],
    role: ["메인 페이지 퍼블리싱", "반응형 레이아웃 구현"],
    highlights: ["기술 기업 이미지 반영", "메인 콘텐츠 정렬", "화면 폭별 레이아웃 대응"],
    links: [{ label: "사이트 보기", href: "https://bnrtech2023.cafe24.com/home/" }],
    websiteUrl: "https://bnrtech2023.cafe24.com/home/",
  },
  {
    id: "client-12",
    title: "기업 홈페이지 리뉴얼",
    category: ["design", "development"],
    thumb: "/projects/sample-12.png",
    summary: "서브 페이지 디자인과 반응형 퍼블리싱을 함께 진행했습니다.",
    tags: ["Design", "Publishing"],
    role: ["서브 페이지 디자인", "반응형 퍼블리싱"],
    highlights: ["기업 정보 재배치", "서브 화면 톤 정리", "모바일 대응"],
    links: [{ label: "사이트 보기", href: "https://ienix.com/home/" }],
    websiteUrl: "https://ienix.com/home/",
  },
  {
    id: "client-13",
    title: "관세/물류 기업 홈페이지",
    category: ["design", "development"],
    thumb: "/projects/sample-13.png",
    summary: "기업 소개 구조에 맞춰 서브 페이지 디자인과 퍼블리싱을 제작했습니다.",
    tags: ["Design", "Publishing"],
    role: ["서브 페이지 디자인", "반응형 퍼블리싱"],
    highlights: ["전문 서비스 소개 구조", "기업형 레이아웃", "콘텐츠 가독성 정리"],
    links: [{ label: "사이트 보기", href: "http://www.jlcustoms.co.kr/home/" }],
    websiteUrl: "http://www.jlcustoms.co.kr/home/",
  },
  {
    id: "client-14",
    title: "식품 브랜드 홈페이지",
    category: ["design", "development"],
    thumb: "/projects/sample-14.png",
    summary: "메인/서브 페이지 디자인과 반응형 퍼블리싱을 담당했습니다.",
    tags: ["Design", "Publishing"],
    role: ["메인 페이지 디자인", "서브 페이지 디자인", "반응형 퍼블리싱"],
    highlights: ["식품 브랜드 이미지 반영", "제품 소개 화면 구성", "브랜드형 레이아웃"],
    links: [{ label: "사이트 보기", href: "https://www.godsauce.co.kr/home/" }],
    websiteUrl: "https://www.godsauce.co.kr/home/",
  },
  {
    id: "client-15",
    title: "산업 기업 홈페이지",
    category: ["development"],
    thumb: "/projects/sample-20.png",
    summary: "기업 홈페이지 기본 화면과 반응형 퍼블리싱을 구현했습니다.",
    tags: ["Publishing"],
    role: ["반응형 퍼블리싱", "기업형 화면 구현"],
    highlights: ["회사 소개 중심 구조", "기본 페이지 반응형 대응", "운영 가능한 화면 구성"],
    links: [{ label: "사이트 보기", href: "https://fourstec2025.mycafe24.com/home/" }],
    websiteUrl: "https://fourstec2025.mycafe24.com/home/",
  },
  {
    id: "client-16",
    title: "랜딩 페이지",
    category: ["design", "development"],
    thumb: "/projects/sample-21.png",
    summary: "전환 목적의 긴 스크롤 랜딩 페이지를 디자인하고 구현했습니다.",
    tags: ["Design", "Landing"],
    role: ["랜딩페이지 디자인", "반응형 퍼블리싱"],
    highlights: ["긴 스크롤 흐름 구성", "전환 중심 콘텐츠 배치", "모바일 가독성 조정"],
    links: [{ label: "랜딩 페이지 보기", href: "/projects/full-21.png", external: false }],
    websiteUrl: "/projects/full-21.png",
  },
  {
    id: "client-17",
    title: "전자 카탈로그",
    category: ["design", "development"],
    thumb: "/projects/sample-15.png",
    summary: "제품 탐색에 필요한 전자 카탈로그 화면을 제작했습니다.",
    tags: ["Design", "Catalog"],
    role: ["전자카탈로그 디자인", "퍼블리싱"],
    highlights: ["제품 탐색 UI", "카탈로그형 레이아웃", "브랜드별 화면 구성"],
    links: [{ label: "카탈로그 보기", href: "https://dxee.cafe24.com/e-cata/beaubeau_en/" }],
    websiteUrl: "https://dxee.cafe24.com/e-cata/beaubeau_en/",
  },
  {
    id: "client-18",
    title: "전자 카탈로그",
    category: ["development"],
    thumb: "/projects/sample-16.png",
    summary: "제공된 디자인을 기반으로 카탈로그 페이지를 퍼블리싱했습니다.",
    tags: ["Publishing", "Catalog"],
    role: ["전자카탈로그 퍼블리싱"],
    highlights: ["제품 페이지 구현", "카탈로그 탐색 구조", "반응형 레이아웃"],
    links: [{ label: "카탈로그 보기", href: "https://dxee.cafe24.com/e-cata/cox_kr/" }],
    websiteUrl: "https://dxee.cafe24.com/e-cata/cox_kr/",
  },
  {
    id: "client-19",
    title: "전자 카탈로그",
    category: ["development"],
    thumb: "/projects/sample-17.png",
    summary: "영문 제품 카탈로그의 반응형 화면을 구현했습니다.",
    tags: ["Publishing", "Catalog"],
    role: ["전자카탈로그 퍼블리싱"],
    highlights: ["영문 콘텐츠 화면", "제품 탐색 UI", "반응형 화면 구성"],
    links: [{ label: "카탈로그 보기", href: "https://dxee.cafe24.com/e-cata/luxrobo_en/" }],
    websiteUrl: "https://dxee.cafe24.com/e-cata/luxrobo_en/",
  },
  {
    id: "client-20",
    title: "전자 카탈로그",
    category: ["design", "development"],
    thumb: "/projects/sample-18.png",
    summary: "브랜드 이미지에 맞춘 전자 카탈로그 디자인과 구현을 진행했습니다.",
    tags: ["Design", "Catalog"],
    role: ["전자카탈로그 디자인", "퍼블리싱"],
    highlights: ["브랜드 톤 반영", "제품군 화면 구성", "카탈로그 UI 구현"],
    links: [{ label: "카탈로그 보기", href: "https://dxee.cafe24.com/e-cata/shinhanelectronic_en/" }],
    websiteUrl: "https://dxee.cafe24.com/e-cata/shinhanelectronic_en/",
  },
  {
    id: "client-21",
    title: "전자 카탈로그",
    category: ["design", "development"],
    thumb: "/projects/sample-19.png",
    summary: "제품군을 빠르게 살필 수 있는 카탈로그형 UI를 제작했습니다.",
    tags: ["Design", "Catalog"],
    role: ["전자카탈로그 디자인", "퍼블리싱"],
    highlights: ["제품군 탐색 구조", "카탈로그 화면 디자인", "반응형 퍼블리싱"],
    links: [{ label: "카탈로그 보기", href: "https://dxee.cafe24.com/e-cata/sunwoo_en/" }],
    websiteUrl: "https://dxee.cafe24.com/e-cata/sunwoo_en/",
  },
];
